// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

package gofumpt_test

import (
	"bytes"
	"embed"
	"testing"

	"github.com/go-openapi/testify/v2/assert"
	"github.com/go-openapi/testify/v2/require"

	"github.com/go-openapi/codegen/formatting"
	"github.com/go-openapi/codegen/formatting/enable/gofumpt"
)

// sources holds the Go the tests format. A fixture is a file so that it reads as the Go it is; the
// .input extension keeps gofmt away from source that is deliberately misformatted.
//
//go:embed testdata
var sources embed.FS

func source(t *testing.T, name string) string {
	t.Helper()

	content, err := sources.ReadFile("testdata/" + name + ".input")
	require.NoError(t, err)

	return string(content)
}

func TestEnable(t *testing.T) {
	t.Run("should apply the rules once the package is imported", func(t *testing.T) {
		require.NoError(t, gofumpt.Configure(gofumpt.WithLangVersion("go1.25")))

		out := format(t, source(t, "generated"), formatting.WithGoFumpt())

		assert.Contains(t, out, "x := []int{1, 2, 3}", "gofumpt tightens the composite literal")
	})

	t.Run("should apply an extra rule when asked for it by name", func(t *testing.T) {
		require.NoError(t, gofumpt.Configure(
			gofumpt.WithLangVersion("go1.25"),
			gofumpt.WithExtraRules("group_params"),
		))

		assert.Contains(t, format(t, source(t, "generated"), formatting.WithGoFumpt()), "func F(a, b int)")
	})

	t.Run("should leave the parameters alone without the extra rule", func(t *testing.T) {
		require.NoError(t, gofumpt.Configure(gofumpt.WithLangVersion("go1.25")))

		assert.Contains(t, format(t, source(t, "generated"), formatting.WithGoFumpt()), "func F(a int, b int)")
	})

	t.Run("should format a generated file, which the gofumpt command would skip", func(t *testing.T) {
		require.NoError(t, gofumpt.Configure())

		out := format(t, source(t, "generated"), formatting.WithGoFumpt())

		assert.Contains(t, out, "// Code generated by go-swagger; DO NOT EDIT.", "the header survives")
		assert.Contains(t, out, "x := []int{1, 2, 3}", "and the rules still ran")
	})

	t.Run("should reject a rule gofumpt does not know", func(t *testing.T) {
		err := gofumpt.Configure(gofumpt.WithExtraRules("no_such_rule"))

		require.Error(t, err)
		assert.Contains(t, err.Error(), "no_such_rule")
	})

	t.Run("should keep the previous settings when an option fails", func(t *testing.T) {
		require.NoError(t, gofumpt.Configure(gofumpt.WithExtraRules("group_params")))
		require.Error(t, gofumpt.Configure(gofumpt.WithExtraRules("no_such_rule")))

		assert.Contains(t, format(t, source(t, "generated"), formatting.WithGoFumpt()), "func F(a, b int)")
	})

	t.Run("should still prune and group", func(t *testing.T) {
		require.NoError(t, gofumpt.Configure())

		out := format(t, source(t, "grouped"),
			formatting.WithGoFumpt(), formatting.WithImportGroups("github.com/go-openapi"))

		assert.NotContains(t, out, `"strings"`)
		assert.Contains(t, out, "\t\"context\"\n\n\t\"github.com/go-openapi/swag/conv\"\n")
	})
}

func format(t *testing.T, src string, opts ...formatting.Option) string {
	t.Helper()

	var out bytes.Buffer

	_, err := formatting.Format(&out, []byte(src), opts...)
	require.NoError(t, err)

	return out.String()
}
