// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// Command gen writes packages.go from "go list std".
//
// Run it with "go generate ./internal/std" after a Go release adds packages to the standard library.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func main() {
	out, err := exec.Command("go", "list", "-f", "{{.ImportPath}} {{.Name}}", "std").Output()
	if err != nil {
		log.Fatalf("go list std: %v", err)
	}

	names := make(map[string]string)

	for line := range strings.SplitSeq(strings.TrimSpace(string(out)), "\n") {
		importPath, name, ok := strings.Cut(line, " ")
		if !ok || name == "main" {
			continue
		}

		// nothing outside the standard library may import these, so they would only pad the table
		if strings.HasPrefix(importPath, "internal/") || strings.Contains(importPath, "/internal/") ||
			strings.HasPrefix(importPath, "vendor/") || strings.Contains(importPath, "/vendor/") {
			continue
		}

		names[importPath] = name
	}

	paths := make([]string, 0, len(names))
	for importPath := range names {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)

	var buf bytes.Buffer
	buf.WriteString(`// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

// Code generated by "go generate ./internal/std". DO NOT EDIT.

package std

// names maps every importable standard library path to the name its package clause declares.
var names = map[string]string{
`)

	for _, importPath := range paths {
		fmt.Fprintf(&buf, "\t%q: %q,\n", importPath, names[importPath])
	}

	buf.WriteString("}\n")

	source, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("cannot format the generated table: %v", err)
	}

	if err := os.WriteFile("packages.go", source, 0o600); err != nil {
		log.Fatal(err)
	}

	log.Printf("wrote packages.go with %d standard library packages", len(paths))
}
