// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// Command gen writes packages.go from "go list std".
//
// It asks once per platform and merges the answers, because the standard library is not the same
// everywhere: runtime/cgo is absent on windows and syscall/js exists only on js/wasm. Merging keeps
// the table the same whoever regenerates it, so "go generate" on a Mac does not churn the file.
//
// Run it with "go generate ./internal/std" after a Go release adds packages to the standard library.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"runtime"
	"sort"
	"strings"
)

// platforms covers the standard library between them. linux carries runtime/cgo, js/wasm carries
// syscall/js, and darwin and windows are there to catch anything either of them holds alone.
var platforms = []struct{ goos, goarch string }{
	{"linux", "amd64"},
	{"darwin", "arm64"},
	{"windows", "amd64"},
	{"js", "wasm"},
}

func main() {
	names := make(map[string]string)

	for _, platform := range platforms {
		for importPath, name := range listStd(platform.goos, platform.goarch) {
			if seen, ok := names[importPath]; ok && seen != name {
				log.Fatalf("%s declares %q on %s/%s and %q elsewhere",
					importPath, name, platform.goos, platform.goarch, seen)
			}

			names[importPath] = name
		}
	}

	paths := make([]string, 0, len(names))
	for importPath := range names {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

// Code generated by "go generate ./internal/std". DO NOT EDIT.

package std

// GeneratedFor names the Go release this table was read from, as in "go1.27".
//
// A later release adds packages the table does not hold, and [Name] then answers false for them,
// which leaves the formatter guessing rather than wrong. TestTableMatchesToolchain checks the table
// exactly on this release and checks only the names they share on any other.
const GeneratedFor = %q

// names maps every importable standard library path to the name its package clause declares.
var names = map[string]string{
`, minorVersion(runtime.Version()))

	for _, importPath := range paths {
		fmt.Fprintf(&buf, "\t%q: %q,\n", importPath, names[importPath])
	}

	buf.WriteString("}\n")

	source, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("cannot format the generated table: %v", err)
	}

	if err := os.WriteFile("packages.go", source, 0o600); err != nil {
		log.Fatal(err)
	}

	log.Printf("wrote packages.go with %d standard library packages", len(paths))
}

// minorVersion trims a Go version to its minor release: "go1.27.0" becomes "go1.27".
func minorVersion(version string) string {
	parts := strings.SplitN(version, ".", 3)
	if len(parts) < 2 {
		return version
	}

	return parts[0] + "." + parts[1]
}

// listStd returns the importable standard library of one platform, keyed by import path.
func listStd(goos, goarch string) map[string]string {
	command := exec.Command("go", "list", "-f", "{{.ImportPath}} {{.Name}}", "std")
	command.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch)

	out, err := command.Output()
	if err != nil {
		log.Fatalf("go list std for %s/%s: %v", goos, goarch, err)
	}

	names := make(map[string]string)

	for line := range strings.SplitSeq(strings.TrimSpace(string(out)), "\n") {
		importPath, name, ok := strings.Cut(line, " ")
		if !ok || name == "main" {
			continue
		}

		// nothing outside the standard library may import these, so they would only pad the table
		if strings.HasPrefix(importPath, "internal/") || strings.Contains(importPath, "/internal/") ||
			strings.HasPrefix(importPath, "vendor/") || strings.Contains(importPath, "/vendor/") {
			continue
		}

		names[importPath] = name
	}

	return names
}
